### ISSUE TITLE
Improve display of pauses in the reader window

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#110]
Currently, if there is a pause of more than the equivalent of five spaces, the code reader displays a double underscore. There are two problems with this:

1. Pauses this short happen quite often and flagging them this way is distracting. The threshold should be longer, perhaps ten spaces.
1. The double underscore is also used to flag missing packets. There should be a different notation to represent long pauses.

**Comment by AESilky** [comment]
What about
``` ~~ ```

**Comment by leskerr** [comment]
The tildes certainly look nice. There are two problems. The first is that the tilde is already used to represent opening the circuit. The stickier problem, that I still haven't got my head around, is for the MKOB app to have a reliable way to distinguish (from information it receives from the code reader) between a long pause and a missing packet. I can think of a quick and dirty solution, but I can't bring myself to stoop so low (yet).

**Comment by AESilky** [comment]
and/or - what if missing packets were flagged by something like:
``` || ```, ``` |/| ```, ``` |+| ```, ``` |O| ```, ``` |!| ```, ``` ▒ ```, ``` ░ ```, ``` □ ```, ``` ≈ ``` or something (other than two underscores)?

**Comment by AESilky** [comment]
Oh, I thought a missing packet would be when you receive (say):
* Packet 1
* Packet 2
* Packet 4

Upon receiving 'Packet 4' the missing packet symbol would be displayed (Packet 3 was missing) and then it would continue displaying the content of Packet 4.
