### ISSUE TITLE
Trap invalid characters in numeric fields

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#117]
MKOB produces a system error if the user accidentally enters a nonnumeric character in the WPM or Wire No. fields in the GUI window. Although the program keeps running, this situation should be handled more gracefully.

**Comment by AESilky** [comment]
I also ran into a 'divide by zero' error when I was changing the speed from 30 to 20. With the value of '30' currently in the input I clicked between the '3' and '0' and hit 'backspace' to remove it. My goal was to then enter a '2' to change from '30' to '20' - but when I hit backspace (removing the '3') I got a DBZ error and the app stopped working.

It's typical for applications to ignore input until the focus leaves the input field. This would resolve this problem. If the focus does leave the field with a '0' value, then the value can be checked at that point and a message displayed.

**Comment by leskerr** [comment]
I agree. The input should be ignored until focus leaves the input field. Good suggestion!

Of course, if the user clicks on one of the up or down spinbox arrowheads, that needs to be processed immediately. But that's a different thing.

**Comment by AESilky** [comment]
Yes. In that case the value should be valid so it can be applied immediately. The wire should have a check to not let it go below 1 (is there an upper limit?). The speed should have a lower and upper limit (maybe it already does).

**Comment by leskerr** [comment]
The WPM widget is currently limited to values ranging from 5 to 40. Wire numbers go from 1 to 32000. These limits constrain the up/down spinner arrows. I'm not sure what happens if you type in a value outside that range. Maybe we need a separate check in that case.

**Comment by AESilky** [comment]
This was fixed some time ago. Not sure of the exact version.
