### ISSUE TITLE
Option to enable/disable use of external kob/key/sounder

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#119]
It would be convenient to leave the 'port' value configured but be able to enable and disable its use. This would allow disabling the KOB and use the simulated sounder (such that headphones can be used in order to not disturb others).

A bonus would be the ability to keep the KOB (loop interface) enabled for the key, but disable the sounder and use the simulated sounder.

This would allow sending with the KOB key while using the simulated sounder with headphones in order to send/practice without disturbing others.

**Comment by leskerr** [comment]
I think this would be a useful feature. I can see myself using the external key with headphones instead of the sounder (or with the speaker with the volume turned low).

**Comment by pwdirks** [comment]
Is it possible to leave the loop enabled and read the key but not create sound on the sounder?  Wouldn't the opening/closing of the key make sound in the sounder if they're wired in a loop?

Is there a diagram of the typical sounder interface?

**Comment by leskerr** [comment]
I never considered the possibility before, but now that I realize it should be possible to read the key in the loop without the loop being powered (meaning the sounder will remain silent). In fact, this is how it works when a remote station opens the circuit. The local sounder stays deenergized, but the program still has access to the state of the local key, and that state is conveyed to the remote station. So yes, it should work.

There's a circuit diagram for a sounder driver interface [here](https://sites.google.com/site/morsekob/morsekob25/interface?authuser=0#h.p_BVV-h37Wxtzn). It's a lot simpler than the loop interface which has superseded it.

**Comment by pwdirks** [comment]
Oh, it's possible to create an output-only sounder driver from a serial port that's different from creating a local loop with Chip Morgan's interface box?  I was picturing the latter, not the former.  When you have a local loop, they key is typically in that loop, no?  And then the key and the local sounder are active/inactive as a pair?

Do people wire the sounder and the key to different pins of the same serial driver (signaling on the "write" and "read" pins, respectively)?  Or do people use separate serial lines for each?

**Comment by leskerr** [comment]
The serial port pin assignments are shown [here](https://sites.google.com/site/morsekob/morsekob25/interface?authuser=0#h.p_H_ETGDx8Vdst). Only one serial port is used. These assignments are the same for all interface configurations (key only, key and sounder driver, or loop interface).

The option for silencing the sounder while still using the key should work with either a sounder driver or a loop interface. If that seems counterintuitive, welcome to the club. Before designing the loop interface, I thought it would be impossible too. But when I saw the circuit for the old dial-up Morse terminal unit I realized it could be done.

**Comment by AESilky** [comment]
I agree.

I put a scope on the loop interface I built and with RTS false (sounder off) the signal on DSR still changes when the key is closed and opened. So it seems like it would just be a matter of splitting out the enabling of the key and the sounder with separate flags rather than using that fact that 'port' is set to enable/disable both.

**Comment by AESilky** [comment]
@pwdirks the key thing with the loop interface is that there is always some current available to flow through the sounder if the loop is closed, just not enough to cause it to energize (click). This allows the interface to sense the circuit being opened/closed either by the closer or by tapping/releasing the knob. 

However, if the loop is open (the closer is open and the knob is up) the sounder cannot be driven. That isn't the case when a separate key and sounder interface is used. In that case, there isn't a loop, so the sounder doesn't depend on the key being closed.

**Comment by AESilky** [comment]
So, with either the loop interface or separate key and sounder interfaces we should be able to allow the port to be configured while still providing an option to enable/disable the sounder output. That allows the port to be configured and remain configured rather than having to clear it out to disable the sounder (which then also disables the key).

**Comment by leskerr** [comment]
@AESilky You're right on all those points.

As far as options are concerned, we already have the `--sound` and `--sounder` options to enable/disable the audio and the sounder. The way `--sounder` is currently implemented should be changed along the lines of your proposal for keeping the port configured so the key is still active.

MKOB's 'Circuit Closer' checkbox effectively controls whether the key is active. It still needs to be implemented. Similarly, the 'Code Sender On' checkbox controls whether the keyboard is active. It too needs to be implemented.

The other config option we need is `--echo`, to support the sounder driver scenario.

**Comment by AESilky** [comment]
I'm trying to think (it hurts)... I understand the need for 'echo' when using the sounder (only) interface, but would it also be needed with the loop/kob interface or is that automatic in that case?

So 'Circuit Closer' is needed in addition to the closer on the key? Or is that only for simulating the closer when there isn't a physical key present?

I would like to be able to keep 'port' configured (so I don't need to track down the correct value each time I want to use it after clearing out the value in order to disable the sounder. If the port is configured but isn't found I think a simple status message saying that it wasn't found and the key-sounder will not be available is adequate (rather than the error message that is currently output).

Maybe a discussion on these options along with how the three different 'latched' flags work would be a good zoom session?

-Ed

**Comment by AESilky** [comment]
When using a separate sounder, is there a case where you would want the sounder enabled and not want the local key sounded. I just figured it would always be echoed such that, if the sounder is enabled, you get the incoming code from the wire as well as the code from the local key sounded. If the sounder is disabled, you don't get any sounder output.

**Comment by leskerr** [comment]
> I'm trying to think (it hurts)... 

Now you know what it's like for me all the time! :-)

>
> I understand the need for 'echo' when using the sounder (only) interface, but would it also be needed with the loop/kob interface or is that automatic in that case?

'echo' is neither necessary nor desirable when using a loop interface. It's preferable to have the loop constantly energized in this case, although it seems to work even if the sounder output to the interface follows the input from the key.
> 
> So 'Circuit Closer' is needed in addition to the closer on the key? Or is that only for simulating the closer when there isn't a physical key present?

It's only needed when the key doesn't have its own shorting lever. This makes more sense in the context of MorseKOB's history, which spans almost twenty years and largely reflects my own history with American Morse. For most of that time, none of my keys had a shorting switch. My workaround was to add the 'Circuit Closer' checkbox. I found it awkward to use the mouse to click on the checkbox at the beginning and end of each transmission, so I added the option of using the Escape key to toggle the state of the checkbox. This worked out very well in practice.

For reasons that made sense at the time, I also used the Escape key to regain control of the wire if a remote user left the circuit open. This too has been a very useful feature. However, this overloading of the function of the Escape key seems unfortunate in retrospect. I think separate keys should be used for the two functions, but honestly I can't decide which function should be assigned to the Escape key and which key should be used for the other function. I don't have a feel for how many users are getting by without a circuit closer on their key; I do know that users in general appreciate being able to regain control of the wire and they instinctively reach for the Escape key when it's occasionally needed. Decisions, decisions...

> 
> I would like to be able to keep 'port' configured (so I don't need to track down the correct value each time I want to use it after clearing out the value in order to disable the sounder. If the port is configured but isn't found I think a simple status message saying that it wasn't found and the key-sounder will not be available is adequate (rather than the error message that is currently output).

I totally agree with this.

> 
> Maybe a discussion on these options along with how the three different 'latched' flags work would be a good zoom session?

Definitely!

> 
> -Ed

~Les

**Comment by leskerr** [comment]
> When using a separate sounder, is there a case where you would want the sounder enabled and not want the local key sounded. I just figured it would always be echoed such that, if the sounder is enabled, you get the incoming code from the wire as well as the code from the local key sounded. If the sounder is disabled, you don't get any sounder output.

I can't think of a case where you'd want the sounder enabled but not have it follow the key.

**Comment by AESilky** [comment]
This was implemented some time ago. Not sure of the exact version.
