### ISSUE TITLE
MKOB: Add Record/Play to MKOB interface

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#137]
Issue #104 developed the `recorder` module. This is to add it into the MKOB GUI so a user can turn recording on/off and play back a recording as though it was live.

I envision a 'Record/Play/Pause' button at the bottom of the GUI with something that lets you select the file.

**Comment by leskerr** [comment]
It would be nice to have 'go back 10 seconds' and 'go forward 10 seconds' buttons, in addition to the 'Pause' button. This would allow replaying a snippet that you want to listen to more carefully.

Not quite so important, but also handy during playback would be a display of the current position in the recorded file (in seconds) and the time left to play.

**Comment by AESilky** [comment]
`Play...` has been added to menu and `ctrl-p` and `ctrl-s` keyboard hotkeys for pause and stop are enabled.
Still work to do for record options and playback controls in GUI.

**Comment by AESilky** [comment]
Playback movements are added and keyboard hotkeys are enabled.
`ctrl-h`: Move back 15 seconds
`ctrl-l`: Move forward 15 seconds
`ctrl-j`: Move to the beginning of the current sender (station)
`ctrl-k`: Move to the end of the current sender (station)
(The keys are the same as many console/tty text editors use to move backward/forward/up/down.)

Still need to add Record/Play control bar to the GUI.

**Comment by AESilky** [comment]
Starting and ending the recording of a session is now controlled using the **File** menu. There is a section for *Record* with items to start and end recording in addition to play.

**MKOB 4.3.1**
