### ISSUE TITLE
Extract Configure.py CLI options processing into a library class

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#14]
It would be convenient to allow individual PyKOB commands/utilities to allow command line options to override the global configuration settings (configured using Configure.py, stored in the two .INI files, read by the 'config.py' module, and made available to the commands).

For example: the user might have used `Configure.py` (via `configure.cmd` or `configure.sh`) to set 'SPEED' (WPM) to '20', but for the `Time.py` program they would like to temporarily speed it up to 25 WPM. Being able to use the `--speed 25` option on the `Time.py` launch to set the speed to 25 just for this instance rather than changing the user's saved preferences would be useful.

Issue 'Default command-line option parsing to override configured defaults #13' should depend on this issue, rather than duplicating the options processing code in each application.

**Comment by AESilky** [comment]
@pwdirks I will make this issue a dependency of #13. The difference PyKOP applications should use a common class/library rather than implementing the option processing individually (and duplicating code).

**Comment by leskerr** [comment]
I haven't absorbed all the details and ramifications of what's being discussed here, but my sense is that you're on the right track. It's often the case that a user will want to run several instances of a program (or more than one program) simultaneously, each with different settings (speeds, ports, etc.) Being able to override the config settings as command line parameters is a useful feature.

It will also be necessary for the MKOB program to update the default configuration settings as they're changed by the user in the course of using the program. This is so that parameters such as Station ID, WPM, and Wire No., etc., can be preserved between sessions.

**Comment by pwdirks** [comment]
Exactly - I think the MKOB GUI and the individual modules should rely on the same configuration file and the same module for setting it.  The GUI would presumably have a "Preferences" panel that's pre-loaded using the config module with the current settings where the user can change values for PORT, WPM, CHAR_SPEED, SOUND ON/OFF, WIRE, etc. and when you hit "OK" that calls the standard config code to update the config file so it's all in sync and there's only ONE single config file with the user's settings.

As for overriding them on the command line, I think that is convenient; I see Ed's point that some parameters will be meaningless for some programs but I don't care if the user can supply them and they're parsed and ignored but if you really want we could let programs call in with some indication of which params they want to accept from the command line.

**Comment by AESilky** [comment]
The `config` module contains the `saveConfig` method that saves out the configuration to the 'user' and 'machine' configuration files. These are split because the configuration of something like 'port' is based on the machine and therefore is the same no matter what user is running the program. That is what is used by the `configure.py`, the same can be called by the MKOB code to save the user's preferences out to the configuration files.

**Comment by pwdirks** [comment]
If we play it right, pykob/configure.py should have the code to save/restore config options and the command-line overrides for individual program's ArgumentParsers.  Typical usage would then be for a program like Clock.py to restore the config options, parse any overrides that make sense, set the local values accordingly, and be off.  Configure.py code should be able to use it without first restoring it (to start clean) or even attempt restoring the saved config and do nothing but invoke ALL of the predefined overrides to let the user set all options before saving the new settings?

I'll experiment a bit in Clock.py with this new model.

**Comment by AESilky** [comment]
`config.py` currently has the functions `readConfig` and `saveConfig`. The `configure.py` calls those methods as needed and parses the options. I was thinking we would move the parsing into `config.py` as 'standard options' and add the ability to pass options to remove from the complete set. This will cause `config.py` to ignore those options and put them into a list of options+values that were present but in the ignore list. 

The `configure.py` wouldn't 'remove' anything from the standard options and in addition would locally parse the options to list the current configurations and system information, and would save the configuration if appropriate.  

Other applications would indicate to ignore any options that aren't applicable so they won't be processed to modify the configuration.

I was also wanting to do something with `-h` `--help` processing, so the 'standard options' help is processed by `config.py` (so it is consistent and isn't duplicated) and the application can handle help for any options it has in addition to the standard options.

**Comment by AESilky** [comment]
I notice that `configure.py` provides `-h` `--help` options to provide help about usage of the application and available options. However, other applications (`sample.py`, `clock.py`, etc.) don't provide this same option.

To be consistent across all PyKOB applications, the `-h`/`--help` option processing should be part of the common options.

**Comment by pwdirks** [comment]
It's actually provided for implicitly when you use argparse.  See, for instance, my prototype for how we should join configuration and command line option processing in Clock.py:

> $ python3 Clock.py -h
> 2020-05-04 09:19:22 Starting Clock
> usage: Clock.py [-h] [-p portname] [-a sound] [-s speed] [-b time] [-e time] [-i minutes] [-t]
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -p portname, --port portname
>                         The name of the serial port to use
>   -a sound, --sound sound
>                         'ON' or 'OFF' to indicate whether morse audio should be generated
>   -s speed, --speed speed
>                         The morse send speed in WPM
>   -b time, --begin time
>                         Beginning of time announcements
>   -e time, --end time   End of time announcements
>   -i minutes, --interval minutes
>                         The time announcement interval in minutes
>   -t, --text            Whether to print text locally as it's sent to the sounder

so when we switch to consistently using the 'config' module and 'argparse' throughout, '-h' will automatically be taken care of.

**Comment by AESilky** [comment]
See comment in #13 for resolution details.
