### ISSUE TITLE
Add 'KeyboardInterrupt' handlers to all applications/commands

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#15]
The PyKOB applications/commands (`Time.py`, `News.py`, etc.) should gracefully handle the `KeyboardInterrupt` to exit.

Currently, many of the apps/commands produce a Traceback when ^C is used to exit.

**Comment by leskerr** [comment]
I agree this should be done. The only reason I never handled Ctrl-C more gracefully is due to laziness on my part and lack of requests from users.

**Comment by pwdirks** [comment]
Well, you've got two picky users now who've been spoiled by long exposure to proper ^C handling... :-)

**Comment by leskerr** [comment]
Actually, just one picky user is all it takes to convince me!  :-)

**Comment by AESilky** [comment]
In writing commercial software (at IBM, TRIRIGA, Oracle, PeopleSoft, Calico) we were never allowed to display a stack-trace to an end user. That is considered a security vulnerability. If testing or users ever get a stack-trace it is a priority 1 (critical) issue and must be fixed immediately. We even had a function in our logging that would 'scrub' a stack-trace before it was written to a logfile to remove PII and other information.

I know this isn't commercial software, but I would like to take care of these as we have a chance to. It shouldn't be hard (an encompassing `try` on the user processing code.

**Comment by AESilky** [comment]
@pwdirks I noticed updates to many files (as conflicts to my issue #12). Do those changes complete/close this issue, or are there still some apps to update?

**Comment by pwdirks** [comment]
Yeah - sorry; wrapping large bodies of code in a try ... except block unfortunately changed the indentation on a lot of code you must've changed for #12 as well.  If you can do a comparison ignoring blank space changes you should find the differences almost negligible but I don't know if the merge tool works strictly on whole lines or is smart enough to merge in only the extra indentation I had to add.

In any case, that merge completed this issue.
