### ISSUE TITLE
Invert key input (DSR) for use with MODEM

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#150]
Using a MODEM to convert old dialup Morse (MODEM) recordings to the PyKOB data file format requires that the key input value from DSR be inverted to match the 'MARK' and 'SPACE' defined by the RS-232 standard.

This is a temporary change while we convert a number of saved audio dialup Morse recordings.

**Comment by AESilky** [comment]
@leskerr would rather not implement a full-featured 'MODEM' interface option (as MKOB 2.5 had) - but, in order to easily convert the archive of dial-up (modem) recordings to the PyKOB recording format - it would help to have an option that can be set rather than switching to a dedicated branch. This is needed because the 'KEY' signal from the recordings is inverted from the current 'key' input.

I seperate 'Invert Key Input' config option will allow setting up dial-up conversion by selection the 'Key and/or Sender' interface and the 'Invert Key Input' options.

**Comment by jchausler** [comment]
Gee, I even used the modem interface option a few times but haven't had to use it lately...  Before the Canadian hub died early this year I occasionally (but only much less occasionally successfully) linked MorseKOB to the Canadian hub this way.  But it was about three or four years ago that I did this last and I was never able to get a successful connection to the hub on any Morse Day.  I think Ed Trump was the last one to try and failed on a Morse Day.73, Chris-----Original Message-----

**Comment by leskerr** [comment]
Adding a separate invert key input config option as suggested, rather than adding a `modem` interface type like MorseKOB 2.5, makes perfect sense. I like it.
