### ISSUE TITLE
Provide 'speed_factor' parameter to recorder.play to allow playback speed adjustment

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#152]
When playing back recordings sometimes the speed of the code is too fast for the person that is trying to copy it. It would be helpful if a `speed_factor` value could be passed in. The value would be a percentage of the recorded speed that the code should be played back at. So a value of '100' would play back at 100% (the same speed it was recorded at). A value of 66 would play back at 2/3rds the speed the code was recorded at.

**Comment by AESilky** [comment]
@leskerr I am adding in the speed_factor parameter (and a CLI option for it in `play.py`) and figured I would add the 'max_silence' parameter and option at the same time, since it will touch the same files/methods. That will allow specifying how much silence to 'play' (including not condensing at all in order to play back exactly as recorded). However, I notice that the timestamp is no longer used as part of the silence time to wait for. I know you spent a lot of time getting this to play as accurately as possible so I didn't want to put the timestamp back in without consulting with you.

Here is the code for reference:
```
                pause = -code[0] / 1000.0  # delay since end of previous code sequence and beginning of this one
                # For short pauses (< 1 sec), `KOB.sounder` can handle them more precisely.
                # However the way `KOB.sounder` handles longer pauses, although it makes sense for
                # real-time transmissions, is flawed for playback. Better to handle long pauses here.
                # A pause of 0x3777 ms is a special case indicating a discontinuity and requires special
                # handling in `KOB.sounder`.
                if pause > 1.0 and pause < 32.767:
                    # For very long delays, sleep a maximum of 5 seconds
                    # ZZZ - 5 second msx will be configurable
                    if pause > 5.0:
                        print("Realtime pause of {} seconds being reduced to 5 seconds".format(round(pause, 3)))
                        pause = 5.0
                    time.sleep(pause)
                    code[0] = -1  # Remove pause from code sequence since it's already handled
```
Looking at this, it seems like only pauses less than 33 seconds will be considered in the check. What if they want to pause up to a minute?

**Comment by leskerr** [comment]
@AESilky Do whatever you think is best. I have no objection to using the timestamp for calculating pauses longer than a second or so.
