### ISSUE TITLE
MKOB: Provide MorseKOB wire list in MKOB Help menu

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#160]
There is a link to list the MorseKOB wires. It would be nice to provide the list as a menu item in help (or possibly 'View').

As an additional feature, allow clicking on it to switch the wire and connect.

**Comment by AESilky** [comment]
I access the list with the URL: http://mtc-kob.dyndns.org/

**Comment by leskerr** [comment]
+1

**Comment by AESilky** [comment]
In MKOB, the **Help | Active Wires** item displays the active wires and allows the user to click on a wire to set it in the UI or double-click to set it and connect (or change the connection).

This works when connected to KOBServer 6.6.2 (or newer). That KOBServer supports reading a JSON that includes all of the wire information that is displayed on the web page. When connected to an older KOBServer, MKOB displays a message indicating that the active wire information isn't available.

**MKOB 4.3.1**
