### ISSUE TITLE
MKOB: Reorganize file structure to put MKOB modules/classes at top level of project

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#167]
In order for changes to pykob files to take effect without having to install into the global module store, pykob needs to be a subdirectory of the MKOB files.

Doing so, will also aid in debugging, since it will allow pykob modules/classes to be debugged at the same time as MKOB modules/classes.

**Comment by AESilky** [comment]
I will do this in a separate cloned folder, so I can continue to work with the current structure for other issues and reviews. Only when/if it seems to be a good change do we need to merge this to master.

**Comment by AESilky** [comment]
@leskerr What is the 'setup.py' in the MKOB folder used for? That will conflict with the one in the root that is used to install the pykob modules/classes.

**Comment by AESilky** [comment]
It already makes it easier to debug MKOB. I don't need to create a Visual Code debug configuration specific to running MKOB.pyw. Using the default 'Python: Run current file' debug configuration now works.

**Comment by AESilky** [comment]
The structure change also allows setting breakpoints in pykob module/class code and stopping when they are hit. With the structure change, when MKOB is run, changes to code within pykob is used without having to run `python3 setup.py install` for them to be picked up.

**Comment by leskerr** [comment]
@AESilky I've been wanting to make this change myself (move the MKOB files up one level in the PyKOB file structure) but I didn't want to break what you were working on. I'm very glad you're doing this!

I was going to suggest removing the MKOB setup file. We don't need it.

I was also thinking maybe we should remove the pykob setup file as well, but the argument for doing that isn't quite so clear. If we leave the pykob setup file where it is, just in case we ever need it, I'd like to update its contents. Specifically:

- Get rid of the version number. It's already in the pykob code, and having it in two places seems like a bad idea.
- Add Ed Silky to the author name line.
- Change author_email to 'morsekob+owner@groups.io'.

**Comment by AESilky** [comment]
@leskerr I think this structure is fine. It makes debugging much easier. I don't think most users will be digging into the source, so adding a number of files to the root directory probably won't matter.

I think that if we follow the convention of naming executable files with an initial capital letter and non-executable files with an initial lowercase letter, it makes the directory format easy to follow.
