### ISSUE TITLE
MKOB: Latest sender doesn't move to the bottom of the Senders List

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#173]
When testing the branch to fix #166 that changed windows updates to be message based;
@leskerr noted: When I was sending, my line of the station list didn't get moved to the bottom of the list.

Proper operation is that:
1. The current sender is listed at the bottom of the list
2. Next up the list should be the previous sender
3. The list should continue to move up in the order a station last sent
4. Stations that are connected but haven't sent, should be listed next up the list

**Comment by leskerr** [comment]
5. When a new station connects while a session is in progress, it can be added to the bottom of the list.

**Comment by AESilky** [comment]
Thanks for that, I didn't realize that. So, the order from 'bottom to top' is:
1. Last station(s) connected (even after a current station is sending)
2. Last station to send
3. Stations that have connected and continue to 'ping', but haven't sent

**Comment by leskerr** [comment]
> Thanks for that, I didn't realize that. So, the order from 'bottom to top' is:
> 
> 1. Last station(s) connected (even after a current station is sending)
> 2. Last station to send
> 3. Stations that have connected and continue to 'ping', but haven't sent

That looks right to me. It preserves the desired order in case of a round table session. Whoever's at the top of the list has waited the longest for their turn in the rotation. It would also be okay for newcomers to be placed immediately above the current sender, but the extra complexity may not be worth the effort.
