### ISSUE TITLE
MKOB: Provide installation scripts for Windows users

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#179]
@AESilky and I discussed the question of how to make it easy for users to install and configure the MKOB software. For a number of reasons, we came to the conclusion that it would be better to download the PyKOB repository than to use one of the Python installer utilities.

I offered to create some scripts to make it easy for Windows users who are averse to using console commands. I'm completely new to Windows scripting, but I've come up with something that works which I'll push to the GitHub server for you guys to critique and improve. This will take the pressure off creating a config settings dialog in the MKOB GUI, which we had previously identified as a priority for beta testers.

**Comment by leskerr** [comment]
The `InstallMKOB.cmd` script creates two shortcuts on the desktop: one to run the program and one to open the `scripts` folder. The folder script does not work. For some reason its 'target type' is `File` instead of `Folder`.

In the current version of `InstallMKOB.cmd`, I have commented out a line that works on my computer (it creates a valid folder shortcut) but won't work on anyone else's.

I've struggled mightily to find a solution to this problem. For the sake of my mental health I need to back off for a while.

**Comment by AESilky** [comment]
I'll take a look. Go for a walk and a latte!

**Comment by AESilky** [comment]
I would rather put this in 'program files' than 'Documents', but that is minor. Thanks for all of the work on this. I think this approach is better than trying to package the program. I think it will allow us to add and update single files.

**Comment by leskerr** [comment]
I agree with 'Program Files' long term, but let's leave it in 'Documents' for now. There are times during beta testing when I want the user to look in the folder where the MKOB files are stored, and it's easier for them to find their Documents folder.
