### ISSUE TITLE
Error trap needed in `pykob/morse.py`

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#204]
On wire 11 this evening, MKOB stopped working with this error:

```C:\Users\Les\Documents\GitHub\PyKOB>py mkob.pyw
PyKOB 1.2.14
MorseKOB 4.0.16
Tcl/Tk 8.6/8.6
2020-12-16 18:01:10 INFO:       Record to 'Session-20201216-1801.json'
Exception in thread Internet-DataRead:
Traceback (most recent call last):
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Les\Documents\GitHub\PyKOB\pykob\internet.py", line 89, in callbackRead
    self.callback(code)
  File "C:\Users\Les\Documents\GitHub\PyKOB\kobmain.py", line 101, in from_internet
    Reader.decode(code)
  File "C:\Users\Les\Documents\GitHub\PyKOB\pykob\morse.py", line 179, in decode
    mk = codeSeq[i+1]
IndexError: tuple index out of range
```

The problem seems to be that the program was trying to decode a code sequence from the internet that was more than 50 elements long, which is a violation of the MorseKOB / CWCom protocol.

I don't know what might be causing this error, but a trap should be added to the program to recover gracefully and possibly log helpful diagnostic information.

This seems to be a rare problem. I think we can leave it on the back burner for now.

**Comment by pwdirks** [comment]
I believe this code has been made much more robust as part of the recent 'Preferences' panel changes.  @leskerr, Could you please test again to see if you can evoke an error entering unexpected input in these fields (or their corresponding Preferences dialog settings)?

**Comment by AESilky** [comment]
The problem I run into with configuration is that (in the main window) I delete the value from wire in order to enter a different value. Currently, is seems that each keystroke change is saved. I believe that is excessive - but beyond that it causes an exception when I delete the whole box.

I'm not sure the error @leskerr had is associated with configuration, but maybe (as you suggest) changes in that area fixed this problem.

**Comment by AESilky** [comment]
Error handling for data packet reading was added to handle the orderly shutdown of the class. I haven't seen this exception since that was added.

**pykob version 1.3.4**
