### ISSUE TITLE
Add decoded character to recorded information

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#214]
Although it's not needed for playback, including the decoded character with the other information recorded for a code sequence would make it easer to locate a portion of a session when viewing/searching the file contents.

**Comment by AESilky** [comment]
One problem is that currently, when the code sequence is recorded the character/text hasn't yet been decoded. The code sequence(s) are accumulated in the 'morse' class object until the 'reader' times out (space between characters) at which point the accumulated code sequence(s) is decoded and displayed in the reader.

**Comment by leskerr** [comment]
I'm in the middle of restructuring the decoding algorithm to handle 'nonstandard' code sequences, but the revised algorithm still exhibits that behavior. Not only is there the lag of a character or two, but sometimes a code sequence will result in no characters being decoded, and sometimes it produces two.

**Comment by AESilky** [comment]
Solved the problem mentioned above by recording the decoded character in the Reader's callback method. That method is called once the decoder has accumulated and decoded the code sequence(s).

In reviewing a short recording of Wire 105 it can be seen that certain letters required more that one code sequence.

The character is recorded with an empty code sequence, which is already handled by the playback code (by ignoring it). Therefore, the added 'decoded character' lines in the recording don't have any effect on the playback.

**Comment by AESilky** [comment]
Here is an example of the recording file:
```
{"ts": 1609309429518, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 40, -120, 40, -40, 40]}
{"ts": 1609309429790, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "R", "c": []}
{"ts": 1609309429793, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 120]}
{"ts": 1609309430300, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-306, 120, -40, 40]}
{"ts": 1609309430732, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "T", "c": []}
{"ts": 1609309430735, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 40, -40, 40, -40, 120]}
{"ts": 1609309431166, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "N", "c": []}
{"ts": 1609309431169, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 120, -40, 120]}
{"ts": 1609309431674, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "U", "c": []}
{"ts": 1609309431676, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 120, -40, 40, -40, 40, -40, 40]}
{"ts": 1609309431872, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "M", "c": []}
{"ts": 1609309431874, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 40]}
{"ts": 1609309432304, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "B", "c": []}
{"ts": 1609309432305, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "E", "c": []}
{"ts": 1609309432309, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 40, -120, 40, -40, 40]}
{"ts": 1609309432898, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "R", "c": []}
{"ts": 1609309432900, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 40, -40, 120, -40, 40, -40, 120]}
{"ts": 1609309433402, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-306, 120, -40, 40]}
{"ts": 1609309433756, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": ",", "c": []}
{"ts": 1609309433759, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 40, -40, 120]}
{"ts": 1609309433772, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "N", "c": []}
{"ts": 1609309433772, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "A", "c": []}
{"ts": 1609309434192, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": 2, "t": "", "c": [-153, 120, -40, 120]}
{"ts": 1609309434995, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "_", "c": []}
{"ts": 1609309434996, "w": 105, "s": "Beaufort Scale, 30 wpm, AC", "o": "", "t": "M", "c": []}
```

**Comment by jchausler** [comment]
This delay is no different than the Display Packets function on 2.5, spaced characters in particular usually take two separate packets to send.  The whole purpose of adding the decoded character from my perspective was just to make it easier to manually find a place in the file where I saw "something unusual" happen and see if I can figure out why.  I was doing that with the json files but to find the place for which I was looking I had to manually decode the packets, something the computer is much better at doing (and quicker :-) than I am...
