### ISSUE TITLE
pykob/config depends on Python 3.6

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#22]
Formatted string literals fail with Python 3.5.

**Comment by AESilky** [comment]
Changed `f"{var}"` formatted strings to `"{}".format(var)` to remove the requirement of Python 3.6. This allows pykob to use older version of Python3.

**Comment by AESilky** [comment]
I didn't have a machine running a lower version of Python3 to test with, but I tested that Configure.py still works and prints information correctly, so I merged into master and will close.

We can reopen if we find that there is still a problem.
@leskerr maybe you can test on your Pi that you discovered the issue on.

**Comment by leskerr** [comment]
I'll try it on my Pi while it's still running Python 3.5. If there's a
problem (unlikely) I'll let you know.

~Les

**Comment by leskerr** [comment]
Fix remaining f'...' literals.

**Comment by AESilky** [comment]
I'm curious where you found more? I did a file search of what I had in my project workspace and changed all that it identified. I'll take a look at your changes to see what I missed to try to understand why.

**Comment by leskerr** [comment]
Did you search for `f'` as well as `f"`?

**Comment by AESilky** [comment]
No, that was my mistake. I had forgotten that I had used any in the form f'.

**Comment by pwdirks** [comment]
Don’t feel bad - I double-checked to see if I got your fix with a ‘grep -r’ but only looked for f-double-quote as well :-)

**Comment by AESilky** [comment]
@leskerr can this be closed?

**Comment by leskerr** [comment]
Yes, I'm closing it now.
