### ISSUE TITLE
Need config option for “Automatically connect at startup”. Drop "Local Copy".

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#223]
The current 'config' module offers no configuration option to “Automatically connect at startup” or a “Hardware Interface” (None/GPIO/Serial port) option.  We should add them, and make sure the config/preferences dialog reads/writes these options.

**Comment by pwdirks** [comment]
I guess Configure.py and the various default argument parsing should be updated, too.  Maybe with “--auto-connect=ON/OFF”?  We already have “-a” (for “audio”) and “-A” (for sounder) and “-c” (for “char. speed”); maybe “-C” for “Connect”?  There’s no “-h” or “-H” defined (we’re rapidly approaching the single-letter command option density of “ls” :-)) so I’d propose “--hardware-interface” / “-h” for the “GPIO”/“SERIAL”/“None” argument?

**Comment by AESilky** [comment]
For some of the less frequently used options, I would like to see if there is a way to only support the '--' style.
Using the current arg parsing (which is very nice) '-h' and '--help' bring up the usage help. So that would rule out using '-h' for the hardware interface.

If that's possible, I think there are a few that I would move to that style and free up the '-' option for local application use while still allowing the '--' to set configuration when running the app.

**Comment by AESilky** [comment]
For now, I will add both to the 'general' section of the configuration. However, 'Automatically connect at startup' is really a MKOB (app specific) configuration. It really should be in an application specific section in the config file.

However, the current `config.py` doesn't support application specific configuration settings.

Here is a snip of a current configuration file:
```
[PYKOB]
code_type=AMERICAN
interface_type=KEY_SOUNDER
key_input_invert=OFF
local=ON
char_speed_min=18
remote=ON
server_url=kobserver1.aesilky.net
sound=OFF
sounder=ON
spacing=NONE
station=Instructograph Tape 5.2
wire=125
text_speed=28
```

As can be seen, all of the config values are in the 'PYKOB' section.
There could be (should be) a 'MKOB' section where the 'Automatically connect at startup' value would be stored.

That can be treated as a separate issue, because other config storage changes might make it irrelevant.

**Comment by AESilky** [comment]
Until/unless we can figure out how to add '--' only options, the 'Hardware Interface' probably needs to be '-H'. As mentioned, using the standard option parsing uses '-h' to bring up command help.

**Comment by AESilky** [comment]
Another possibility for the hardware interface would be to overload the port (-p/--port) with a 'special' value that indicated the RPi GPIO should be used.

I'm typically not in favor of using special values, but in this case it might make things easier. People that would be using a RPi probably wouldn't have a problem putting in (something like) 'RP' as a port value. We could extend that to include the loop number (based on the proposal in the RPi discussion in morsekog@groups.io), like 'RP:1' to indicate Raspberry Pi GPIO Loop 1 pins.

That keeps us from adding another configuration property (and associated option). If RPi GPIO is being used the port value wouldn't be.

**Comment by pwdirks** [comment]
Hi Ed,

That’s another possibility, I guess.  Given that everything’s been serial so far, and Les’ comment that putting the ’Serial’ option front-and-center was desirable, maybe doing away with the “--hardware-type”/“-H” option altogether isn’t so bad.  You could leave it unspecified to indicate no HW option (system sound only)?  Then the preferences dialog should probably have a checkmark “Use hardware interface” followed by a list of serial-based options?

Will there be a way to tell whether you’re running on a Raspberry Pi with a GPIO hat, and which pins are available to control pre-seeding the list of pop-ups?  Or should we always just assign the four or so defined pins?

Thoughts?

Regards,
-Patrick.

**Comment by AESilky** [comment]
I think a 'None' value in 'Port' would indicate that there isn't a hardware interface.

I think we can create a module/function that would indicate that we are running on a PI. I would need to think a lot about how to provide a function to say what RPi GPIO loops are available. I think allowing freeform input will be required.

**Comment by AESilky** [comment]
Going to drop the 'Hardware Interface' component requirement of this.

Also, based on other discussions, going to remove the 'Local Copy' value that is currently supported, but hasn't been used by any code. This option doesn't have a good use-case.

**Comment by AESilky** [comment]
I added the 'auto_connect' value to pykob.config, removed the 'local' property.
I updated the Configure.py to allow setting the value and to display it.

I also updated 'kobmain.py' to look at this configuration property and automatically connect if it is True.

**Comment by AESilky** [comment]
I also updated 'kobconfig' to make things work, but I'm not sure what this is for? It seems like it duplicates the 'pykob.config' module. It also seems like it will get in the way of implementing a change notification mechanism.

@leskerr - why does `kobconfig` need to exist?

**Comment by AESilky** [comment]
I tested `Configure.py` to make sure it:
1. Displayed the current value
2. Allowed setting the value to both ON/TRUE and OFF/FALSE
3. Displayed an appropriate help message.

**Comment by AESilky** [comment]
I tested `MKOB` to see if it auto-connected, or didn't, based on the value of the value set using `Configure`.

**Comment by AESilky** [comment]
Can you suggest other applications that should consider the 'auto_connect' value in the configuration?

**Comment by leskerr** [comment]
> I also updated 'kobconfig' to make things work, but I'm not sure what this is for? It seems like it duplicates the 'pykob.config' module. It also seems like it will get in the way of implementing a change notification mechanism.
> 
> @leskerr - why does `kobconfig` need to exist?

@AESilky `kobconfig` is used in `kobwindow`, `kobactions`, and `kobmain`. I don't have a good answer for you on why it exists. It may be an artifact from an early version of MKOB, before `pykob.config` arrived on the scene. It appears to have been retrofitted to get its values from `pykob.config`. It could be deleted if all the references to `kobconfig` are updated to access `pykob.config` directly.

**Comment by AESilky** [comment]
This seems like a good issue to use to remove `kobconfig`. I will do that and update the pull request.
