### ISSUE TITLE
MKOB: Make changes in Main window "sticky" in config

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#228]
Changes in the main window (to wire #, station ID, etc.) should immediately be updated in the config files so the next invocation of MKOB will find them as they were left during the last run.

This will also simplify the model for Preferences/Configuration: the Preferences window loads from the config-file settings, so this will ensure the Preferences window starts in sync with the main window.  Picking up changes in configuration AFTER the Preferences window has been run should be handled as part of introducing the Preferences window.

**Comment by AESilky** [comment]
This seems to be working. I changed the 'wire' and then checked with `Configure.py` and it reported the new value.

Can we close this, or is there more testing you want to do? I didn't change and check every value, but if we find ones that aren't 'sticky' we can create an issue for them.

**Comment by pwdirks** [comment]
Resolved with merge of #229 ("Remove dependency on kobconfig; pass through all config options straight from 'config'.").
