### ISSUE TITLE
Preferences: Dialog panel on Linux doesn't show all values and can't be resized.

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#230]
Bringing up the File>Preferences on my Linux laptop doesn't display all of the settings/values.

There isn't a way to resize it (which I would expect for a panel like this), but all of the settings/values need to be visible.

**Comment by pwdirks** [comment]
Can you please spell out which settings are missing?

**Comment by AESilky** [comment]
![MKOB Preferences Linux 230](https://user-images.githubusercontent.com/19332027/104801886-6adbf900-5785-11eb-997a-28035ae15541.png)

This is the entire dialog on my Linux laptop. It is cut off just below 'Automatically connect...`

**Comment by pwdirks** [comment]
Thanks for including a picture!  What’s the size of your screen on that Linux laptop?

73, -Patrick.

**Comment by AESilky** [comment]
Here is the whole screen:
![MKOB Preferences full screen 230](https://user-images.githubusercontent.com/19332027/104806082-b98b9200-5789-11eb-941e-0d7415ae0087.png)

Resolution: 1440x900

**Comment by pwdirks** [comment]
Very strange.  Let me set up an Ubuntu VM and try it on my Mac.

73, -Patrick.

**Comment by AESilky** [comment]
It works on my Mac. The position of the dialog on Windows cuts off the title bar (so I can't move it). I'll take a screen shot on it.

**Comment by AESilky** [comment]
![2021-01-15](https://user-images.githubusercontent.com/19332027/104806435-649d4b00-578c-11eb-8106-ade5442c9dbf.png)

This is on my Windows laptop.
Resolution: 1366x768

**Comment by AESilky** [comment]
I have two other Windows machines I can try it on. For Linux, I can try it on a Raspberry Pi if that would help.

**Comment by pwdirks** [comment]
Weird - it looks OK on my Ubuntu VM (after I installed python3-tk, python3-disutils, python3-serial, and python3-audio):

![image](https://user-images.githubusercontent.com/48630827/104827523-6eb65c80-5813-11eb-8b85-9f953a9ad6df.png)

**Comment by pwdirks** [comment]
You've tried updating to the very latest (3.8?  3.9?) Python and Tkinter/Ttk?

**Comment by AESilky** [comment]
For some reason, the window sizing/positioning calls were causing the dialog to show up partially off screen on some instances of Linux. I've commented them out for now, allowing Tkinter/Tcl and the OS to position them as they see fit, and things are working. The dialog tends to show up near the upper left of the screen, rather than in the center - but it shows up completely and can be moved around.

**pykob version 1.3.4**
