### ISSUE TITLE
MKOB: Implement 'Profiles' (configurations)

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#231]
There is a request to have multiple configurations of the MKOB app that can be run. Each 'environment' would pick up a different configuration.

The goal is to avoid having multiple copies of the code installed (an update headache) unless you actually want to run a different copy of the code.

The proposal is to implement the concept of a 'profile' that could be loaded/selected.

**Comment by leskerr** [comment]
'Profiles' has the fewest syllables. :-) Probably a friendlier term to a lot of users who aren't computer buffs.

**Comment by pwdirks** [comment]
FWIW I like ‘profiles’.  It’s a good, generic term for a number of descriptive attributes.

I don’t know how you plan to implement them but it might be simplest to have multiple stand-alone config files.  In that case you could also just call them “Configs”?

73, -Patrick.

**Comment by AESilky** [comment]
"Profiles" sounds good and I agree separate config files is probably a good approach. 

That is similar to the 'workspace' files in Visual Studio Code and other IDEs. I can start it with a specific one, I can 'save as' one to another and then make changes, and I can load one at any time.

**Comment by pwdirks** [comment]
Profile “X" = Config file “X” also makes for an easy-to-explain semantics for “Save” - it updates the current profile to the new settings.

If you want to, I suppose you could add a “Preference” to switch profiles mid-stream but I think that’s OK to leave for later, too.  For now, it’ll be valuable just to be able to start it with --profile=... or --config=... and be tied to that config file until exit.

73, -Patrick.

**Comment by AESilky** [comment]
(From Kevin Jepson)
Named configuration file or multiple configurations in same file. I am thinking of having my Quadra machines choose different configurations on startup. This would allow things like playing an arbitrary text when running locally, or switching the wire before it auto connects.

**Comment by AESilky** [comment]
The `Config` class in *config2.py* supports 'isolated' configuration. It supports reading the configuration from a 'named' file rather than just to the single *global* configuration.

An option `--config path-to-config-file` allows the applications (MKOB and MRT) and utilities to use different configurations based on a command line option. MKOB also added the ability to load and save different configurations in addition to the *global* configuration.

**pykob version 1.3.4**
**MKOB version 4.3.1**
