### ISSUE TITLE
MKOB: Preferences doesn't set 'Auto-Connect' value in Config.

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#235]
If I set the 'Auto-Connect' value using the CLI Configure.py and start MKOB it does/doesn't auto-connect as expected. However, the value doesn't show correctly in the 'Preferences' dialog and changes in the dialog are not made to the configuration.

**Comment by pwdirks** [comment]
Fixed with merge of branch #247 from MorseKOB/pwd-#235-Incorporate-new-auto-connect-config-in-preferences-panel
