### ISSUE TITLE
If the preferences window is minimized ('iconified'), selecting 'Preferences' does not show the window as expected

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#245]
What's missing is a call to 'deiconify()' on the window before pulling it to the front.

**Comment by AESilky** [comment]
@pwdirks create a PR for this and it can be merged in.

**Comment by pwdirks** [comment]
Closed w. merge of latest change on branch pwd-243-limit-to-single-preferences-panel-at-runtime.
