### ISSUE TITLE
Config/preferences should be split into General/basic and a separate "Advanced" tab

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#249]
The current preferences dialog shows all available config options.  Some, like the server URL and port, are better moved to a separate "Advanced" tab to avoid unnecessarily cluttering up the basic preferences display.

**Comment by pwdirks** [comment]
I propose we move:

* Invert key input (only used for modem input)
* Server address and port number 

to the advanced tab.  We could also move "Word spacing" - does anyone tweak where Farnsworth spacing is introduced, or is "between characters" the overwhelming favorite?

Should we leave "Code type: American/International" in basic preferences or move it, too, into "Advanced"?

I'm pretty comfortable calling one tab "Advanced" but what should we call the other, which is first shown?  "General"?  "Basic"?  "Common"?  Something else?

**Comment by leskerr** [comment]
Patrick,

The serial port pull-down menu, interface type (loop, key & sounder, or keyer), and audio on/off all need to be on the basic tab. Everything else can move to the advanced tab. Perhaps a separate Farnsworth tab is in order.

And yes, character spacing for Farnsworth is definitely more common.

~Les

**Comment by AESilky** [comment]
I agree, and would add 'sounder' on/off to 'General'.

**Comment by pwdirks** [comment]
Hi guys - have a look at the pwd-#249-Create-tabbed-preferences-with-separate-Advanced-tab branch sometime.  I took a first stab at dividing preferences into "Basic" (maybe we should call it "General", or something else?) and an "Advanced" tab.  I created a separate third tab with all the "Morse Code" options.

Comments about placement of various options (and anything else, of course) would be most welcome.  It's not hard to shuffle things between tabs.

**Comment by leskerr** [comment]
Patrick,

I love the tabs!!

![Preferences](https://user-images.githubusercontent.com/63867213/105617822-3f18ce80-5d96-11eb-9be4-8bd7b69c1c15.png)

Here are some comments:

1. I'd move everything in the 'Internet Connection' panel to the Advanced tab. I can't imagine using any of these options myself, and I'd rather not confuse first-time users with features they're unlikely to use.
- I don't know why I'd want to suppress sending to other stations while I'm connected to a wire. Is it because I want to monitor the wire but not accidentally send something? What's the use case?
- You'll have to tell me one more time what the intial station ID and initial wire number are for. Changes to these settings on the main screen are 'sticky', so they're also used as the 'initial' settings. Why are they in both places?
- I think the main rationale for automatically connecting on startup is for museums to make it easier for docents to start the application. But this seems misguided. Museums should be using a custom application, not the full-featured MKOB client.
2. The station ID box (if it stays) is still too short for me. The same length as the serial port pulldown menu would work.
3. While going back and forth between the preferences panel and the main screen, somehow I got into a situation where 'File > Preferences...' wouldn't bring up the preferences panel. I thought maybe the preferences panel was hidden behind another window, but closing or minimizing the other windows didn't help. I had to close the program and restart it to get the preferences panel back.

~Les

**Comment by pwdirks** [comment]
Hi Les,

Thanks for having a look!

> 1. I'd move everything in the 'Internet Connection' panel to the Advanced tab. I can't imagine using any of these options myself, and I'd rather not confuse first-time users with features they're unlikely to use.


OK - done.

> • I don't know why I'd want to suppress sending to other stations while I'm connected to a wire. Is it because I want to monitor the wire but not accidentally send something? What's the use case?


It controls the ‘remote’ setting - I believe that’s tied to having your circuit closer close (i.e. “Connect” indication is red)?

> • You'll have to tell me one more time what the intial station ID and initial wire number are for. Changes to these settings on the main screen are 'sticky', so they're also used as the 'initial' settings. Why are they in both places?

Now that the options are ’sticky’ it’s no longer ‘Initial’.  I’ve removed that word.  It’s just another way to control the same setting as the wire # and station ID in the main window (but without forcing you to exit preferences first)

> • I think the main rationale for automatically connecting on startup is for museums to make it easier for docents to start the application. But this seems misguided. Museums should be using a custom application, not the full-featured MKOB client.


Oh, I’m not sure if that’s the only use case (and I don’t think that’s so terrible) - I could also see having MorseKOB start at boot and just directly connect.  One less step involved.  Same for ‘Feed’, I should think?  Seems harmless to leave it there?

> 2. The station ID box (if it stays) is still too short for me. The same length as the serial port pulldown menu would work.

I’ve made it slightly more than double it’s size - let me know what you think now?

> 3. While going back and forth between the preferences panel and the main screen, somehow I got into a situation where 'File > Preferences...' wouldn't bring up the preferences panel. I thought maybe the preferences panel was hidden behind another window, but closing or minimizing the other windows didn't help. I had to close the program and restart it to get the preferences panel back.

That one’s more worrisome - I wonder if there’s a race between the invocation of the preferences window and the disposal of the last one in the GUI (in separate threads).  Let me know if you hit this again?

Thanks!
-Patrick.

**Comment by leskerr** [comment]
>> • You'll have to tell me one more time what the intial station ID and initial wire number are for. Changes to these settings on the main screen are 'sticky', so they're also used as the 'initial' settings. Why are they in both places?

> Now that the options are ’sticky’ it’s no longer ‘Initial’. I’ve removed that word. It’s just another way to control the same setting as the wire # and station ID in the main window (but without forcing you to exit preferences first)

Changing the wire number on the main window changes the wire number on the preferences panel, but not vice versa. The same thing is true of the station ID. I think changes on the preferences panel should be reflected immediately on the main window (assuming you click on Save and not Cancel).

BTW, once again I got stuck in a mode where 'File > Preferences...' wouldn't bring up the preferences panel. I wish I knew exactly what I was doing before that happened, but it had something to do with switching back and forth between the main window and the preferences panel. I'll try to pay more attention in the future in case it happens again.

**Comment by pwdirks** [comment]
Hi Les,

Yes, having the changes immediately picked up is what issue #236, MKOB: Pick up changed 'config' values dynamically. <https://github.com/MorseKOB/PyKOB/issues/236> is all about.  I believe Ed’s working on that.  Ed, do you have some specific grand design in mind for that?  Or should I just go ahead and have the main program re-read the (possibly changed) config options for the values shown in the main display (wire #, station ID, etc.)?  So that’s still on the “to do” list.

Shall I check in the tabbed version of the preferences as a replacement for the current version?  Any further thoughts about what should go where?

Thanks,
-Patrick.

**Comment by AESilky** [comment]
I am in the middle of having the preference changes picked up upon closing the panel. I have enough done that I'd like to finish it. I've just been tied up a bit the last couple days. I will try to finish it tomorrow (I'm tied up again this afternoon).

**Comment by AESilky** [comment]
I think the Station ID box could be the whole window width. I don't see the harm in making it large (rather than limiting it).

**Comment by pwdirks** [comment]
Les reported a problem:

There's a problem with the current 'master' branch. When I run MKOB and bring up the preferences panel, it's extremely small and it doesn't show any of the controls.

![image](https://user-images.githubusercontent.com/48630827/105649319-a8ffa980-5e64-11eb-9d3c-5573c1080cd9.png)

This is with Windows 10.

Also, if I go to 'Files > Preferences...' more than once, it shows multiple instances of the preferences panel.
