### ISSUE TITLE
git should ignore 'log.txt' file

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#25]
git should ignore any log files; Receive.py creates a log file "log.txt".

**Comment by AESilky** [comment]
Note that updating `.gitignore` with the 'log.txt' will keep git from adding it in the future, but it will not remove it from any repos that have already added it.

For those, it will need to be deleted, that change committed, etc.

Also, I would like logging to go into a `log` directory. That way if we have other things that log (possibly libraries, etc.) we can have them go into the `log/` directory so we can find all logging in one place, plus we can '.ignore' the `log/` directory and we won't need to update the `.gitignore` for each different logging file that shows up. Not critical, but I'll add an issue for it.
