### ISSUE TITLE
Inclusion of optional libraries should be guarded with "try ... except" and the functionality disabled if not present

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/PyKOB#250]
Not all libraries used by the PyKOB components are standard on systems with Python: pySerial, pyAudio, and Tkinter are optional additional installs.

Inclusion of references to these libraries should be guarded with try ... except and the functionality not used if the libraries aren't present.

**Comment by AESilky** [comment]
The `pykob` modules do not rely on a graphical interface. It is only MKOB that does (a different module/application).

I don't think any `pykob` modules should import graphic libraries. However, if they do, they should be guarded as you suggest.
