### ISSUE TITLE
Accept non-ASCII characters in station ID

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#258]
I wasn't able to use MKOB 4.0 on wire 11 yesterday. Every time I tried to connect, the program crashed with this error message:

```
  File "C:\Users\Les\Documents\GitHub\PyKOB\pykob\internet.py", line 113, in read
    stnID, sep, fill = stnID.decode(encoding='ascii').partition(NUL)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 17: ordinal not in range(128)
```

The problem was a listener on the wire (legitimately) had non-ASCII characters in his station ID. Specifically, the station ID was 'BG Pierre, Ste-Thérèse'.

This is a fairly high priority bug. I'll try to fix it as soon as I can.

**Comment by AESilky** [comment]
It seems like you should be able to just change the decoding to UTF8.
