### ISSUE TITLE
MRT: Sounder Power-Save Triggers even with Key/Closer Open

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#289]
When the key closer is open, and if the sounder power-save timeout expires, when I go to send the sounder does not operate, but the characters are still sent. Briefly closing the key closer and opening it again restores the sounder to operation.

The other oddness is that sending from that KOB seems to lose parts of the last characters. For example, "Hello" almost always comes out as "Helle". The sounders on the remotes actually sound that as well so it isn't a decoding artifact.
Connecting the same KOB and interface to MKOB 4 or MorseKOB 2.5 on windows does not result in the same behavior.

**Comment by AESilky** [comment]
This issue was reported via morsekob@groups.io by Kevin Jepson.

**Comment by AESilky** [comment]
I believe I fixed this in the es-mrt branch, and I pushed it to master. I'll wait for @kevijeps to test before I close this.

**Comment by Kevijeps** [comment]
Initial testing shows that the behaviour no longer occurs.
Timeout does not effect sounder when Key is open.
