### ISSUE TITLE
MRT: Sending sometimes drops the last dot of a spaced chacter so Y comes out as C and O as E 

### ISSUE THREAD

**Issue by Kevijeps** [MorseKOB/PyKOB#295]
Using PyKOB MRT on the Quadra connected to a physical keysounder loop using a Chip Morgan Interface.
When sending spaced characters as the last character of a word it will often drop the last dot.
So HELLO becomes HELLE and THEY becomes THEC.
It receives OK from another sender.
MorseKOB 2.5 does not actually receive the last dot as it never gets sent by PyKOB.

**Comment by AESilky** [comment]
You mention MRT... Does it also happen with MKOB? I can test if needed.

**Comment by Kevijeps** [comment]
I have tested it with MKOB and it does not appear to have the same behaviour.

**Comment by Kevijeps** [comment]
Hi Ed
I just tested MRT.py on my windows machine and it exhibits the same behaviour in that it drops the last dot.
It is only spaced characters that do it so a string of Os ends up as O E E E. The first one seems to be fine but if it follows another character it drops the last dot.
I have the latest MRT.py from here already.

**Comment by AESilky** [comment]
I believe this is fixed. I used a test device that can key much more accurately than I can, and it doesn't seem to be missing the elements after an inter-character space now.

**Comment by Kevijeps** [comment]
Initial testing shows this is indeed fixed!
Well done.
Will test more extensively but so far it looks good.
