### ISSUE TITLE
PyKOB/MKOB/MRT Issues found during testing of version 1.3.1/4.2.1/1.3.1 for release.

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#314]
This single issue will be used to collect small issues found during the (hopefully) final testing before release.

Comments will be added as small issues are found. If any major issues are found, a separate issue will be created to track it. At release, any issues that remain unresolved will be moved into individual issues, so they can be tracked.

**Comment by AESilky** [comment]
1. Computer (synth) sounder occasionally stops sounding open/close circuit, though it does sound the text.
3/13/2024 SB

**Comment by AESilky** [comment]
2. If you have an interface configured, and you don't have it available when you start, it displays the message letting you know, but then the keyboard sender window won't let you type anything. You can fix it by going to the icon/task bar and click on the icon to reselect the window (clicking on the window itself doesn't fix it).
3/13/2024 ES

**Comment by AESilky** [comment]
3. MKOB: Tools > Show Packets not working.
3/13/2024 SB

**Comment by AESilky** [comment]
5. The red connected notification doesn't show when the MKOB is set to autoconnect.
It does connect OK but it doesn't turn red.
If I disconnect and reconnect it shows but not on startup.
3/18/2024 KJ

**Comment by AESilky** [comment]
6. The simulated sounder is whacky it makes a horrible buzzing instead of either the tone or clicks.
MRT is fine though.
3/18/2024 KJ

**Comment by Kevijeps** [comment]
RE No Network Crash

I just tried MKOB without a network in my office and got the same behaviour.
The GUI stops responding before I can get access to anything.
I will try it on another computer and let you know.

**Comment by Kevijeps** [comment]
Just tried with brand new install of bot Python and the current files.
Same behaviour, with no internet connection MKOB stops responding and crashes.
Ciao
KJ

**Comment by Kevijeps** [comment]
Interesting using the current files (with the sound and connection indicator fixes) the no Internet problem seems to be fixed.
I have attached the detailed log for sending FRED, once while connected and once disconnected.
Hopefully that will be useful.
[CWindowsSystem32cmd.exe.txt](https://github.com/MorseKOB/PyKOB/files/14644739/CWindowsSystem32cmd.exe.txt)
