### ISSUE TITLE
Missing MKOB.pyw file

### ISSUE THREAD

**Issue by ChipEckardt** [MorseKOB/PyKOB#370]
With latest build for Linux (Quadra) the MKOB.pyw file is missing.  Did serach sub directories and could not find it any where.

**Comment by AESilky** [comment]
The file was moved to `MKOB.py`. This was done because the `.pyw` extension was causing some libraries to be pulled into the binary that aren't needed for this application.

I will update the README and the _inovato Quadra_ instructions in the MorseKOB group.
