### ISSUE TITLE
MKOB - Need to add license header

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#43]
All of the MKOB files need the license header.

**Comment by leskerr** [comment]
I'd like to make this simple change myself, just for practice with Git/GitHub. I assume I do the following:

1. Pull the mkob branch to make sure I'm working from the latest version.
2. Make the changes locally.
3. Commit the changes.
4. Push the branch to origin (GitHub).
5. Post a Pull Request. (I don't know if I need to specify reviewers, or if that happens automatically.)
6. After the changes are approved, I merge the branch into master.
7. Push master to GitHub.

Does that sound right to you guys? Please give me feedback if I wander astray. Thanks!

**Comment by pwdirks** [comment]
A few points, just to be sure:

Step 2: make sure you create a (local) branch to do your work on.  That lets you push JUST the branch up to the GitHub server.  The changes should be committed on that local branch.

Step 3: You have to specify who you'd like to get a review from when you create the pull request on the web site.  Ed and I should be listed as your collaborators.

Step 6: After you merge the branch into the master branch on GitHub you have an option to delete the branch from the GitHub server.  Feel free to go ahead and do so - no reason to keep these short-lived branches around on the server.'

Step 7: That's actually backwards, at least from how I do it.  The 'pull request' is a request ON THE GITHUB SERVER to merge the branch there.  Step 7 should be "Pull the updated master from GitHub", followed by step 8: "Delete the local branch created in Step 2".

Hope that's clear?

**Comment by AESilky** [comment]
I agree - but would add to 'Step 6:'...
After the review is approved you can click the 'Merge' in the issue on GitHub and it will merge your branch into master and then tell you you can delete the branch and give you the option to do that. That deletes it from GitHub. You can then checkout master on your machine, pull to update your master from GitHub (now with your changes merged), then delete your working branch on your local machine.

**Comment by leskerr** [comment]
Got it. I think I have a better understanding of the workflow now. Thanks!
