### ISSUE TITLE
MKOB:Windows - Provide 'application install and launcher'

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#48]
Provide an easy way to install the components needed to run PyKOB and run it.

This should check/install Python, the needed libraries, the application and provide a launch application so users don't need to use a command like `python3 mkob.py` to run the application.

**Comment by AESilky** [comment]
Parent: #44

**Comment by AESilky** [comment]
I have created a first cut at a PyInstaller implementation to create a Win-32 and a Win-64 bundle that includes MKOB and Configure.

**Comment by AESilky** [comment]
The windows scripts run fine and create a Win32 and Win64 bundle. There is a fair amount of build machine setup required, but there doesn't seem to be a way around that.

The Mac script creates a Mac bundle - however, there are problems when you try to run it. It displays a dialog box indicating that Apple can't verify the publisher and will not run it. Looking into this, I sound that there is a process you can do in security settings to get around the warning, but it's not straightforward. However, when I did it, I received an additional error on the Python that was packaged into the bundle. I haven't found a way to get past that error, so I'm not able to run from the bundle.

I put the Mac bundle in the shared folder. @pwdirks, maybe you can give it a try and see if you have any ideas on how to fix it.
https://1drv.ms/f/s!AqnBbsz_ABrPhKxwJXVv7IaZ2JNX0Q

I will work on the Linux bundle.

**Comment by leskerr** [comment]
@AESilky Are the scripts for creating the bundles located somewhere in the PyKOB project on GitHub?

**Comment by AESilky** [comment]
Yes - Windows and Mac are. I haven't put one together for Linux yet.

pyinstall/README.md
pyinstall/w/make.cmd
