### ISSUE TITLE
Setup - Update setup.py files

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#51]
Someone more knowledgeable than myself needs to overhaul the setup files `pykob/setup.py` and `mkob/setup.py`.  All details of these files need to be revisited (version no., etc.) but in particular I should not be listed as the sole author. Also, I don't know how these setup files relate to the broader issue #44 of providing installation capabilities for different platforms.

**Comment by AESilky** [comment]
Working this in conjunction with #44 makes sense.
