### ISSUE TITLE
MKOB: Wire connection doesn't use station name specified

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#53]
When connecting to a wire MKOB (python) uses "AC Les - Seattle, WA" even though a different station name was specified.

Steps to replicate:
1. Enter a station name in the text box (not labeled, but defaults to "AC Les - Seattle, WA" when MKOB is started)
2. Select a wire using the 'Wire No.' spinner (used '10' for the test)
3. Connect
4. On a different machine run MorseKOB 2.5 (the Windows application)
5. Connect to the same wire (using a station name different from the one specified in 1. and not "AC Les - Seattle, WA"
6. Monitor the upper-right text box (un-labeled 'stations connected' list)
7. Notice that the station list (eventually) displays "AC Les - Seattle, WA" as one of the two stations rather than the station name specified in 1.

**Comment by AESilky** [comment]
I have an initial (quick) change that resolves this. I will fix a few things up and submit this change, but would rather this be handled with the introduction of a 'Context' object that holds the values for `wire` and `station` and 'etc...'.

[Windows MKOB-2.5]
![image](https://user-images.githubusercontent.com/19332027/84636182-24e64c00-aea9-11ea-90fa-1fe0f68f0fba.png)

**Comment by leskerr** [comment]
Well, this is awkward. I worked on issue #71 (save and restore settings) over the weekend. Among other things, these changes address the present issue (#53, which unfortunately I had forgotten about). I pushed a commit of my changes late yesterday, but wanted to do a bit more testing today before creating a pull request.

I'm going to need some help untangling the mess I've gotten myself into. It may be time for a Zoom session.

**Comment by AESilky** [comment]
I will pull your branch and take a look. Did you move the station name to Internet.connect (as I did) or did you address it by creating a new Internet object each time with the station name?

**Comment by leskerr** [comment]
> Did you move the station name to Internet.connect (as I did) or did you address it by creating a new Internet object each time with the station name?

Neither. I'm ashamed to admit I updated the class attribute `Internet.officeID` through a direct assignment. It crossed my mind that I could/should have created a new method to do this assignment within the class, but my intent on this go-around was to get MKOB working without making any changes to the core pykob modules. I knew this would all change once we agree on how to handle config settings.

I did use the `pykob.config` module to fetch and save the settings. I'm sure I did this in a clumsy way, but it worked for my purposes and I realize the code needs a seriously cleanup and it's all subject to change. At the risk of causing you to recoil in revulsion, here's the code I added to `kobactions`:

```
def doOfficeID(event=None):
    global myInternet
    kc.OfficeID = kw.varOfficeID.get()
    config.set_station(kc.OfficeID)
    config.save_config()
    myInternet.officeID = kc.OfficeID.encode(encoding='ascii')
```

By the way, MorseKOB 2.5 users sometimes change their station ID while connected to the server. I do this myself on occasion. There are several reasons for wanting to do this. A good example is when you want to change your status to indicate that you're temporarily unavailable.

I'm sorry if I wasted your time while you're so busy with other projects.

**Comment by AESilky** [comment]
I think we can add a 'set' method on `Internet` without changing the rest of your code. We can close this issue with your change and I'll back mine out.

I'll pull your branch and test it out. I can check adding a 'set' method and make sure that works. I can then push that change (on your branch) and we can merge it to master.
