### ISSUE TITLE
Station list sometimes fails when changing wire numbers

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#82]
If you're receiving a feed on one wire and then switch to a different wire without disconnecting, the station list sometimes retains the ID of the previous feed.

**Comment by AESilky** [comment]
@leskerr can you provide a quick step-by-step (minimal detail is fine) to try to replicate this? I'm wondering if my threading/message changes might have fixed this.

**Comment by leskerr** [comment]
If you're connected to a wire and then change to a different wire (by entering a different wire number or by clicking on the up or down arrows by the wire number box), the stations that were connected to the previous wire remain in the station list until they time out.

The station list should be cleared when changing wires, just like it's cleared when you disconnect from a wire.
