### ISSUE TITLE
Enums should have numeric values to be used by PyKOB/MKOB directly

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#97]
The configuration enums currently have text values ('INTERNATIONAL'/'AMERICAN'). Seeing these in use by MKOB/PyKOB/CLI code, they are testing the text values and converting to a number.

Rather than having each of the applications do that, the enum 'value' can be changed to a number and the application code can use the `.value` of the enum. The few parts that need the name (the load/save config) can use the `.name` value.

**Comment by AESilky** [comment]
Looking at the recent changes to MKOB the following changes seem appropriate:  
 `config.char = 0`. 
 `config.word = 1`. 
 `config.none = 2`  

 `config.american = 0`. 
 `config.international = 1`. 

This will require small changes to the read/save in 'config', but will make the applications simpler. They can either same/compare to the enum or use the numeric value without doing further processing.

**Comment by AESilky** [comment]
@leskerr I think you can move forward with what you currently have in #92 and we can adjust when we put this in.

**Comment by leskerr** [comment]
@AESilky If I had know about enums, I probably should have used them for the PyKOB library instead of numeric values. I'm not sure if it's too late for a wholesale retrofit. Maybe changing the config enums to numeric values, as you suggest, is a reasonable compromise. I leave it up to you to decide what's best.

**Comment by AESilky** [comment]
Tested with MKOB, Configure, and Clock.
